### ISSUE TITLE
Problem to convert Decimal to int64.

### ISSUE THREAD

**Issue by thiagoalvesp** [xavierjefferson/Hangfire.FluentNHibernateStorage#1]
Hi,

I installed Hangfire.FluentNHibernateStorage and I use oracle Personal Oracle Database 11g Version 11.1.0.6.0 - Production.
When I try to use the BackgroundJob and RecurringJob classes, I get the return of a conversion error.
When type of property is Long the Nhibernate create column number (20,0) in database. I believe that is the problem.
I noticed that in the past the ID property was INT. Can not you go back?
![decimaltoint64](https://user-images.githubusercontent.com/10868308/36790486-baff3dde-1c73-11e8-826b-460bfcfe2a8a.JPG)

**Comment by CharcoalUchiha** [comment]
I'm having the same issue using this package for my .NET web application.  Have you resolved this yet?  

I'm going to see if I can edit Xavier's code, and fix the issue.  I'm new on here, and don't have a lot of time; so I won't be able to provide a contribution or anything.  If I'm able to fix the issue, I'll post my solution here.

**Comment by CharcoalUchiha** [comment]
I found the source of the issue.  It's actually being caused by another GitHub package; Nhibernate-Core.  This package calls the nhibernate-core inside of its SessionWrapper class --> Insert Method.

You could try fixing the nhibernate-core's BasicSetter.Set Method, but I think it may be easier to just implement the is in Fluent's SessionWrapper.Insert Method.

I'm going to take a break from this - been working on it since 7am.  I will try implementing a fix inside of the Insert Method, and let you know if it works.

**Comment by CharcoalUchiha** [comment]
Okay, I'm back.  I tried the download/fix/copy DLL approach, but it didn't work; there were too many bugs with Xavier's code; like I said earlier, I don't have a lot of time, so fixing 30+ bugs would have been too time consuming.  I'm going to fork this package instead.

The link is below; it will take me a while to learn how to do this fork process properly, so it should be ready for you to test by tomorrow morning:

[https://github.com/CharcoalUchiha/Hangfire.FluentNHibernateStorage](url)

**Comment by CharcoalUchiha** [comment]
Okay, I just submitted the Pull Request for the fork I made.  Here's the link:

[https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage/pull/4](https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage/pull/4)

**Comment by CharcoalUchiha** [comment]
Hello,

I canceled the pull request.  I have created a new [Hangfire.Oracle](https://github.com/CharcoalUchiha/Hangfire.Oracle) repo.  It's still in testing-phase, but should have it working within a week or two.  I'll keep thread alive until I have it running without abEnding.

**Comment by CharcoalUchiha** [comment]
@thiagoalvesp, awesome!  How did you resolve the issue?  Also, is it available in NuGet?

**Comment by thiagoalvesp** [comment]
@CharcoalUchiha  I revert this commit https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage/commit/a602062d5a39acdd4137aeba8a0230641f3dad88#diff-225751ec0d220b06c68a9987e231286d
Change long to int.

**Comment by CharcoalUchiha** [comment]
@thiagoalvesp thanks.  I will move forward using your fork.  I'm not sure if Xavier saw your commit, but he definitely did not apply it to the NuGet package.  I'll keep **Hangfire.Oracle** available for anybody else that comes across this issue.  Thanks again!!!

**Comment by CharcoalUchiha** [comment]
It worked, but there were other issues arising with insertion.  One of the issues is common among Hangfire, but the other issue(s) is being caused by FluentNHibernate.  To that end, I am going to develop an Oracle Scheduler for ASP.Net web apps. Thanks @thiagoalvesp for responding, and for the help you provided yesterday.  I truly appreciate it!  Take care!

**Comment by thiagoalvesp** [comment]
it's awensome @CharcoalUchiha , good luck in your new project. It was nothing!

**Comment by CharcoalUchiha** [comment]
Thanks @thiagoalvesp!  After spending a couple of days away from this, I came back, and figured out how to fix the issues I was having.  The common Hangfire issue can be avoided my not including any Http or WebUI types inside of the methods being invoked by Hangfire.  Doing that also prevented the FluentNHibernate issue from occurring.  With that, I can continue to use your fork of Hangfire.FluentNHibernate, and I won't have to grind out a completely new Oracle Scheduler.  Thanks again!

**Comment by xavierjefferson** [comment]
Updated Nuget package
