### ISSUE TITLE
Bad DefaultSchema does not create tables and does not throw errors.

### ISSUE THREAD

**Issue by rtaylor72** [xavierjefferson/Hangfire.FluentNHibernateStorage#11]
I had a typo in the DefaultSchema setting, and had "could not execute" errors because the tables did not exist.

I think this should throw an exception if the schema does not exist so you know the issue.

**Comment by xavierjefferson** [comment]
This was addressed in upstream package Snork.FluentNHibernateTools v 1.1.8655
