### ISSUE TITLE
IsolationLevel.Snapshot throws ORA-08177: can't serialize access for this transaction

### ISSUE THREAD

**Issue by rtaylor72** [xavierjefferson/Hangfire.FluentNHibernateStorage#12]
When I tried to use IsolationLevel.Snapshot connecting to Oracle 12c (12.1.0.2.0) using the "Hello world from Hangfire!" example, I get an exception error thrown:
**ORA-08177: can't serialize access for this transaction**

I was able to switch to Serializable, but not sure if this is an issue trying to use Snapshot.

**Comment by mabakay** [comment]
Oracle 12c does not support Snapshot isolation level. You could use Serializable but it is pessimistic.
