### ISSUE TITLE
Wrong statistics on dashboard when using oracle instead of memory storage

### ISSUE THREAD

**Issue by mabakay** [xavierjefferson/Hangfire.FluentNHibernateStorage#13]
I have switched from memory storage (where everything was working fine) to oracle (using OracleClient10Managed). I understand that counters can be delayed, but what I get does not look right.

![image](https://user-images.githubusercontent.com/1766645/58308994-476f7800-7e03-11e9-8cd0-69b9cb786930.png)

![image](https://user-images.githubusercontent.com/1766645/58309049-6968fa80-7e03-11e9-924e-3392f12a2cba.png)

Hangfire version:
![image](https://user-images.githubusercontent.com/1766645/58309078-7d146100-7e03-11e9-9e3f-171b915eb06d.png)

**Comment by mabakay** [comment]
In addition the lists are in ascending order.

**Comment by xavierjefferson** [comment]
You rock!  I put this out on Nuget as 1.1.2400.
