### ISSUE TITLE
.Net core Support

### ISSUE THREAD

**Issue by Core0001** [xavierjefferson/Hangfire.FluentNHibernateStorage#17]
Hi,

I was looking at converting my existing project to use FluentNHibernateStorage as sometimes I am required to connect to an Oracle databases.

After installing the package against my .Net Core 3 project I get a couple of warnings ,Is this package compatible with .Net core?

Thanks for you help
Alex

![2019-12-16_12-20-20](https://user-images.githubusercontent.com/51349245/70872897-0dfc9500-1fff-11ea-8c92-c5685af1dcb2.png)

**Comment by xavierjefferson** [comment]
That's an excellent question.  I haven't tried it out on .Net core at all.
Would you let me know what, if any, issues you encounter?

Thanks.

**Comment by ganchito55** [comment]
Hi, I have tried to use this lib with .NET Core 2.2 and for me It didn't work. There is a problem using Snork.FluentNHibernateTools with .NET Core but I think that I fixed it in [this PR](https://github.com/xavierjefferson/Snork.FluentNHibernateTools/pull/2)

**Comment by xavierjefferson** [comment]
Updated to .NET standard
