### ISSUE TITLE
Oracle Support ContinueWith and MonitoringApi

### ISSUE THREAD

**Issue by hugoj-goncalves** [xavierjefferson/Hangfire.FluentNHibernateStorage#2]
There seems to be some issues with Oracle Support.

- [ ] [Hangfire.FluentNHibernateStorage\Hangfire.FluentNHibernateStorage\Monitoring\FluentNHibernateMonitoringApi.cs) -> UseStatefulTransaction -> IsolationLevel.ReadUncommitted](https://github.com/xavierjefferson/Hangfire.FluentNHibernateStorage/blob/a274d3aaaf8229d205b16cc199cb9e79e38fb91e/Hangfire.FluentNHibernateStorage/Monitoring/FluentNHibernateMonitoringApi.cs#L332)
    - As far as I know Oracle doesn't support ReadUncommitted...
- [ ] After a succesful Job it does not trigger the ContinueWith Job defined.

I didn't test others drivers tough.

**Comment by xavierjefferson** [comment]
Try changing the initialization option

var options = new FluentNHibernateStorageOptions
            {
                TransactionIsolationLevel = IsolationLevel.ReadCommitted,
            };

**Comment by hugoj-goncalves** [comment]
That option is not honored at that point.

**Comment by rshivarkar** [comment]
to honor your given storage change code in FluentNHibernateMonitoringApi.cs
I have given IsolationLevel.ReadCommitted when getting storage object  and its working for me.


 private T UseStatefulTransaction<T>(Func<SessionWrapper, T> action)
        {
          //  return _storage.UseTransaction(action, IsolationLevel.ReadUncommitted);
            return _storage.UseTransaction(action, _storage.Options.TransactionIsolationLevel);
        }

**Comment by xavierjefferson** [comment]
Updated Nuget package
