### ISSUE TITLE
LazyInitializationException in monitor

### ISSUE THREAD

**Issue by fcavallari-italcom** [xavierjefferson/Hangfire.FluentNHibernateStorage#21]
I have an exception in monitor when access to job detail (.../hangfire/jobs/details/xx) in version 1.2.1020.

The exception is:
LazyInitializationException: Initializing[Hangfire.FluentNHibernateStorage.Entities._Job#30]-failed to lazily initialize a collection of role: Hangfire.FluentNHibernateStorage.Entities._Job.Parameters, no session or session was closed.

I'm using Hangfire.AspNetCore v.1.7.22 in a Net Core 3.1 Web Api application.

**Comment by jvbraganca** [comment]
Hey @fcavallari-italcom were you able to solve it? I have the same problem.

**Comment by fcavallari-italcom** [comment]
Hi @jvbraganca,
sorry but I abandoned the idea of ​​using nHibernate for HangFire persistence in my Web Api application. 
Maybe this works fine on Desktop App where nHibernate session is handled in different way.
