### ISSUE TITLE
How to Prevent Docker Containerized Version from Exiting?

### ISSUE THREAD

**Issue by princefishthrower** [xavierjefferson/Hangfire.FluentNHibernateStorage#22]
This is more a question of my own sanity, or perhaps I don't fully understand how this package works.

The provided example:

```c#
using System;
using System.Configuration;
using System.Transactions;
using Hangfire.FluentNHibernateStorage;

namespace Hangfire.FluentNHibernate.SampleApplication
{
    public class DemoClass
    {
        private static BackgroundJobServer _backgroundJobServer;

        private static void Main(string[] args)
        {
            //Configure properties (this is optional)
            var options = new FluentNHibernateStorageOptions
            {
                TransactionIsolationLevel = IsolationLevel.Serializable,
                QueuePollInterval = TimeSpan.FromSeconds(15),
                JobExpirationCheckInterval = TimeSpan.FromHours(1),
                CountersAggregateInterval = TimeSpan.FromMinutes(5),
                UpdateSchema = true,
                DashboardJobListLimit = 50000,
                InvisibilityTimeout = TimeSpan.FromMinutes(15),
                TransactionTimeout = TimeSpan.FromMinutes(1),
                DefaultSchema = null, // use database provider's default schema
                TablePrefix = "Hangfire_"
            };

            //THIS SECTION GETS THE STORAGE PROVIDER.  CHANGE THE ENUM VALUE ON THE NEXT LINE FOR
            //YOUR PARTICULAR RDBMS

            var PersistenceConfigurerType = ProviderTypeEnum.MsSql2012;
            var connectionString = ConfigurationManager.ConnectionStrings["someConnectionString"].ConnectionString;
            var storage = FluentNHibernateStorageFactory.For(PersistenceConfigurerType, connectionString, options);

            //THIS LINE CONFIGURES HANGFIRE WITH THE STORAGE PROVIDER
            GlobalConfiguration.Configuration.UseStorage(storage);

            /*THIS LINE STARTS THE BACKGROUND SERVER*/
            _backgroundJobServer = new BackgroundJobServer(new BackgroundJobServerOptions(), storage,
                storage.GetBackgroundProcesses());

            /*AND... DONE.*/

            Console.WriteLine("Background job server is running.  Press [ENTER] to quit.");
            Console.ReadLine();
        }
    }
}
```

Is supposed to run continuously, correct? I have an example almost identical, except my class is `internal`, and I configure it to run in a docker container. Interesting that the container is exiting even though that`Console.ReadLine()` command is there...

Would love any pointers here when using this package with Docker, as I'm certain the culprit is Docker, as I can run my app in debug from Visual Studio and it does not exit. Obviously, I want my enqueued jobs and the background job server running continuously...

**Comment by xavierjefferson** [comment]
Yeah, that sounds like a Docker issue.  You might find some articles
somewhere about running this kind of application within Docker (basically,
it's like a service application that has to stay alive and poll for
activity).   Good luck

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by princefishthrower** [comment]
Yep, for now, I ended up going with a hack that looks like this:

```csharp
await Task.Run(() => Thread.Sleep(Timeout.Infinite));
```

it's ugly but it runs as expected and will do for now.
