### ISSUE TITLE
Batcher still has opened ressources at time of processing from system transaction.

### ISSUE THREAD

**Issue by s3YwCf2ZbfJG4SHAfjQMAjtsf** [xavierjefferson/Hangfire.FluentNHibernateStorage#24]
https://github.com/nhibernate/nhibernate-core/issues/2750   The error is described here:

Hangfire.FluentNHibernateStorage 1.2.1050 reported the above errors against an Oracle 19 database. I can provide more information about the Oracle environment as needed.

Going back to 1.2.1020 of Hangfire.FluentNHibernateStorage resolved the errors.

Please let me know if I should provide any additional information.

**Comment by xavierjefferson** [comment]
Resolved.  Stateless sessions will now have explicit flush when disposed
