### ISSUE TITLE
The operation is not valid for the state of the transaction

### ISSUE THREAD

**Issue by ArcherTrister** [xavierjefferson/Hangfire.FluentNHibernateStorage#26]
Hangfire: 1.7.28
Hangfire.FluentNHibernateStorage: 1.2.1060

use `Hangfire.SqlServer`,It's ok.

![image](https://user-images.githubusercontent.com/35516482/172521569-50e915c5-031d-4f54-ac30-466a300d0cef.png)

when I use `Hangfire.FluentNHibernateStorage`,It always produces a lot of exceptions.
![image](https://user-images.githubusercontent.com/35516482/172522461-15efe304-e353-4912-aca0-30f296de2663.png)

**Comment by xavierjefferson** [comment]
This is normal behavior.  Because this implementation supports multiple database providers that all have different drivers, there's a brute force approach to handling deadlocks, transaction issues, and similar.
