### ISSUE TITLE
PrepareSchemaIfNecessary = false still creates Hangfire schema

### ISSUE THREAD

**Issue by brownjr38** [xavierjefferson/Hangfire.FluentNHibernateStorage#8]
var options = new FluentNHibernateStorageOptions
            {
                DefaultSchema = MySchema,
                PrepareSchemaIfNecessary = false
            };

Using the above still creates the Hangfire database schema if it didn't previously exist.

**Comment by xavierjefferson** [comment]
Resolved.  Placed in nuget release 1.1.2105

**Comment by brownjr38** [comment]
> Resolved. Placed in nuget release 1.1.2105

Thank you!
