### ISSUE TITLE
Hangfire don't EnQueue on Oracle

### ISSUE THREAD

**Issue by mahmut-gundogdu** [xavierjefferson/Hangfire.FluentNHibernateStorage#9]
` BackgroundJob.Enqueue(() => sayHi());

  public void sayHi()
        {
            string x = "hello" + "world";
            System.Threading.Thread.Sleep(10000);
        }
`

There is  'Hangfire_Job' in oracle. (auto created).

error:
`could not insert: [Hangfire.FluentNHibernateStorage.Entities._Job][SQL: INSERT INTO PORTAL."Hangfire_Job" ("Id", "LastStateChangedAt", "StateData", "InvocationData", "Arguments", "CreatedAt", "ExpireAt", "StateName", "StateReason") VALUES (PORTAL.hibernate_sequence.nextval, ?, ?, ?, ?, ?, ?, ?, ?) returning "Id" into :nhIdOutParam]

`

**Comment by xavierjefferson** [comment]
Did you determine a root cause?

**Comment by mahmut-gundogdu** [comment]
No i did not find. iSession.save() throw error. But it think problem is schema case (Oracle want to uppercase" ) I solved with hangfire.oracle.core so I closed my issue.
